version: '3'
services:
  getshiny:
    networks:
      - proxy
    image: sc-registry.fredhutch.org/getshiny:latest
    environment:
      - SERVICE_EMAIL=scicomp@fredhutch.org
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.getshiny.rule=Host(`getshiny.fredhutch.org`)"
        - "traefik.http.routers.getshiny-secured.rule=Host(`getshiny.fredhutch.org`)"
        - "traefik.http.routers.getshiny.entrypoints=web,web-secured"
        - "traefik.http.services.getshiny.loadbalancer.server.port=8080" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.getshiny.tls=true"

networks:
  proxy:
    external: true
